# Practica de Algebra lineal

### *Nombre*

<span style="color:blue">Ejercicio 1:  
Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales (para la multiplicación)}</style>

In [2]:
import numpy as np

+ Forma 1

In [126]:
def add(v,w):
    return [v[0]+w[0],v[1]+w[1]]
def addn(v,w):
    return [v[i]+w[i] for i in range(len(v))]
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

# alpha∈ℝ, 0≤ alpha ≤1
#alpha = np.linspace(0, 1, 100)
alpha = 0.5

# arrays
v1 = np.array([1, 2])
v2 = np.array([3, 4])

# resultado
addn(mult_vector_escalar(alpha, v1), v2)
#np.asarray(resultado)


[3.5, 5.0]

+ Forma 2

In [122]:
def mult_vector_escalarArray(alpha,v1,v2):
    for a in alpha:
        print( addn([a*v1[i] for i in range(len(v1))],v2) )

# alpha∈ℝ, 0≤ alpha ≤1
alpha = np.linspace(0, 1, 5)
#alpha = 0.5
# arrays
v1 = np.array([1, 2])
v2 = np.array([3, 4])

#addn(mult_vector_escalarArray(alpha, v1), v2)
mult_vector_escalarArray(alpha, v1, v2)

[3.0, 4.0]
[3.25, 4.5]
[3.5, 5.0]
[3.75, 5.5]
[4.0, 6.0]


+ Forma 3 (Final)

In [314]:
[add(mult_vector_escalar(i/float(100),[1,2]),[3,4]) for i in range(11)]

[[3.0, 4.0],
 [3.01, 4.02],
 [3.02, 4.04],
 [3.03, 4.06],
 [3.04, 4.08],
 [3.05, 4.1],
 [3.06, 4.12],
 [3.07, 4.14],
 [3.08, 4.16],
 [3.09, 4.18],
 [3.1, 4.2]]

<span style="color:blue">Ejercicio 2:  
Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:blue">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:blue">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:blue">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:blue">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:blue">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:blue">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:blue">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:blue">que es el mensaje original</style>    
  
 <span style="color:blue">¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [146]:
clave = np.array([0,1,0,0,1,0,1,0,1,0])
mensaje = np.array([0,0,0,1,1,1,0,1,0,1])
cifrado = np.array([0,1,0,1,0,1,1,1,1,1])

# resultado_esperado: [ 0,1,0,1,0,1,1,1,1,1 ]
# mensaje + clave 
# resultado_obtenido: [ 0,1,0,1,2,1,1,1,1,1 ]


# resultado_esperado: [ 0,0,0,1,1,1,0,1,0,1 ]
# cifrado + clave
# resultado_obtenido: [ 0,2,0,1,1,1,2,1,2,1 ]

def perfectSecret(msg, key):
    res = msg + key
    for i in range(len(res)):
        if(res[i]==2): 
            res[i]=0
    return res

# Cifrando...
print( "Cifrando:", perfectSecret(mensaje, clave) )
# Descifrando...
print( "Descifrando:", perfectSecret(cifrado, clave) )

('Cifrando:', array([0, 1, 0, 1, 0, 1, 1, 1, 1, 1]))
('Descifrando:', array([0, 0, 0, 1, 1, 1, 0, 1, 0, 1]))


<span style="color:blue">Ejercicio 3: coste total o beneficio. </style>

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [164]:
def producto_escalar(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))

coste = np.array([2.5,1.5,0.006,0.45])
cantidad = np.array([6,14,7,11])

print("Hacer una cerveza cuesta:", round(producto_escalar(coste, cantidad), 3), "euros")

('Hacer una cerveza cuesta:', 40.992, 'euros')


<span style="color:blue"> Ejercicio 4:   
¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>

In [202]:
import sympy as sp
from __future__ import division
#NOTA
#En python 2.x la division devuelve un valor entero, para corregir esta situación podemos:
# 1.- from __future__ import division
# 2.- Hacer casting del denominado. ex: a / float(b)

def addn(v,w):
    return[v[i]+w[i] for i in range(len(v))]

def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

In [277]:
# A*x = B
# Forma1: usando la libreria sympy
A = sp.Matrix(( (2,1,2), (0,0,2), (1,2,2) ))
B1 = sp.Matrix(3,1,(3,0,0))
B2 = sp.Matrix(3,1,(0,2,0))
B3 = sp.Matrix(3,1,(0,0,1))
x1 = A.LUsolve(B1)
x2 = A.LUsolve(B2)
x3 = A.LUsolve(B3)

print(x1)
print(x2)
print(x3)

Matrix([[2], [-1], [0]])
Matrix([[-2/3], [-2/3], [1]])
Matrix([[-1/3], [2/3], [0]])


In [278]:
# A*x = B
# Forma1: usando la libreria numpy
A = np.matrix([
    [2,1,2],
    [0,0,2],
    [1,2,2]
])

B1 = np.matrix([
    [3],
    [0],
    [0]
])
B2 = np.matrix([
    [0],
    [2],
    [0]
])
B3 = np.matrix([
    [0],
    [0],
    [1]
])

x1 = np.linalg.solve(A,B1)
x2 = np.linalg.solve(A,B2)
x3 = np.linalg.solve(A,B3)

print(x1)
print(x2)
print(x3)

[[ 2.]
 [-1.]
 [ 0.]]
[[-0.66666667]
 [-0.66666667]
 [ 1.        ]]
[[-0.33333333]
 [ 0.66666667]
 [ 0.        ]]


Expresamos las combinaciones lineales en Python

In [230]:
addn(mult_vector_escalar(2,[2,0,1]), mult_vector_escalar(-1,[1,0,2]))

[3, 0, 0]

In [256]:
addn(addn(mult_vector_escalar(-2/float(3),[2,0,1]), mult_vector_escalar(-2/float(3),[1,0,2])), mult_vector_escalar(1,[2,2,2]))

[0.0, 2.0, 0.0]

In [280]:
addn(addn(mult_vector_escalar(-1/float(3),[2,0,1]), mult_vector_escalar(2/float(3),[1,0,2])), mult_vector_escalar(0,[2,2,2]))

[0.0, 0.0, 1.0]

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [333]:
import numpy as np
A = np.matrix([
    [2,-3],
    [-4,6]
])
B = np.matrix([
    [8,4],
    [5,5]
])
C = np.matrix([
    [5,-2],
    [3,1]
])

prod1 = A*B
prod2 = A*C

#PENDIENTE
#inv_A = np.linalg.inv(A)


<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

 $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]  
   , B=
  \left[ {\begin{array}{cc}
   b11 & b12 \\
   b21 & b22\\
  \end{array} } \right]
$  

$
 A*B=
  \left[ {\begin{array}{cc}
   3b11 -6b21 & 3b12 -6b22 \\
   -b11 +2b21 & -b12 +2b22\\
  \end{array} } \right] = 0  
$  

$  
  3b11 - 6b21 = 0 
$  
$
  -b11 + 2b21 = 0
$ 
  
Fijando b21 = 1 tenemos que b11 = 2

$  
  3b12 - 6b22 = 0 
$  
$
  -b12 + 2b22 = 0
$ 

Fijando b22 = 2 tenemos que b11 = 4

In [332]:
A = np.matrix([
    [3, -6],
    [-1, 2]
])
B = np.matrix([
    [2, 4],
    [1, 2]
])
A * B

matrix([[0, 0],
        [0, 0]])

<span style="color:blue"> Ejercicio 7:  
Sarrus para el determinante de orden 3.  
¿Cómo lo haríamos en Python?</style>

In [304]:
A=np.matrix([
   [1,-4,2],
   [-2,8,9],
   [-1,7,0]
   ])
# Calculo de determinante con la funcion det de numpy
np.linalg.det(A)

# Metodo Sarrus para determinante de orden 3
def sarrus(A):
    return ((A[0,0]*A[1,1]*A[2,2])+\
           (A[0,1]*A[1,2]*A[2,0])+\
           (A[0,2]*A[1,0]*A[2,1]))-\
          ((A[2,0]*A[1,1]*A[0,2])+\
           (A[2,1]*A[1,2]*A[0,0])+\
           (A[2,2]*A[1,0]*A[0,1]))

sarrus(A)

-39

<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

Sistema de ecuación 1
> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [334]:

A = np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])

A_amp = np.matrix([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,-9]
])

rankA     = np.linalg.matrix_rank(A)
rankA_amp = np.linalg.matrix_rank(A_amp)

print("Número de incognitas = 3")
print("Rango de la Matriz de coeficientes = " + str(rankA))
print("Rango de la Matriz ampliada = " + str(rankA_amp))

Número de incognitas = 3
Rango de la Matriz de coeficientes = 3
Rango de la Matriz ampliada = 3


Como los rangos de la matriz de coeficientes y de la matriz ampliada son iguales y coinciden con el número de incógnitas podemos concluir que el sistema tiene una única solución.

* Es un Sistema Compatible Determinado.

Sistema de ecuación 2
> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [335]:
A = np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])

A_amp = np.matrix([
    [0,1,-4,8],
    [2,-3,2,1],
    [5,-8,7,1]
])

rankA     = np.linalg.matrix_rank(A)
rankA_amp = np.linalg.matrix_rank(A_amp)

print("Número de incognitas = 3")
print("Rango de la Matriz de coeficientes = " + str(rankA))
print("Rango de la Matriz ampliada = " + str(rankA_amp))

Número de incognitas = 3
Rango de la Matriz de coeficientes = 2
Rango de la Matriz ampliada = 3


Como los rangos de la matriz de coeficientes y de la matriz ampliada son distintos podemos asumir que el sistema no tiene solución.

* Es un Sistema Incompatible.

Sistema de ecuación 3
> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [337]:
A = np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])

A_amp = np.matrix([
    [1,0,1,2],
    [2,3,1,3],
    [3,3,2,5]
])

rankA     = np.linalg.matrix_rank(A)
rankA_amp = np.linalg.matrix_rank(A_amp)

print("Número de incognitas = 3")
print("Rango de la Matriz de coeficientes = " + str(rankA))
print("Rango de la Matriz ampliada = " + str(rankA_amp))

Número de incognitas = 3
Rango de la Matriz de coeficientes = 2
Rango de la Matriz ampliada = 2


Como los rangos de la matriz de coeficientes y de la matriz ampliada son iguales pero es menor al número de incógnitas podemos concluir que el sistema tiene infinitas soluciones.

* Es un Sistema Compatible Indeterminado.

<span style="color:blue"> Ejercicio 9:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

Se define la función r([x,y]) = M ∗ [x, y] = función rotación $\theta$:

* r([1,0]) = [ cos$\theta$, sin$\theta$ ]
* r([0,1]) = [ -sen$\theta$, cos$\theta$ ] 

* Por tanto la matriz M es:
$
  M =
  \left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]
$

r: $\mathbb{R}$<sup>2</sup> $\rightarrow$ $\mathbb{R}$<sup>2</sup>  
r([x,y]) = M ∗ [x, y] = (x*cos$\theta$ - y*sin$\theta$, x*sin$\theta$ + y*cos$\theta$)


En primer lugar podemos observar que la imagen de (0,0) es (0,0). \\
Para verificar que r([x,y]) es una función lineal se tiene que cumplir las siguientes propiedades:

* Propiedad 1: r(u+v) = r(u) + r(v)
* Propiedad 2: r(k.v) = k * r(v)


u = ($u_{1}$, $u_{2}$)  
v = ($v_{1}$, $v_{2}$)

u + v = ($u_{1}$+$v_{1}$, $u_{2}$+$v_{2}$)

r(u + v) =  
= ($u_{1}$+$v_{1}$)*cos$\theta$ - ($u_{2}$+$v_{2}$)*sin$\theta$, ($u_{1}$+$v_{1}$)*sin$\theta$ + ($u_{2}$+$v_{2}$)* cos$\theta$ =  
= $u_{1}$cos$\theta$ + $v_{1}$cos$\theta$ - $u_{2}$sin$\theta$ - $v_{2}$sin$\theta$, $u_{1}$sin$\theta$ + $v_{1}$sin$\theta$ + $u_{2}$cos$\theta$ + $v_{2}$cos$\theta$ =  
= $u_{1}$cos$\theta$ - $u_{2}$sin$\theta$ + $v_{1}$cos$\theta$ - $v_{2}$sin$\theta$, $u_{1}$sin$\theta$ + $u_{2}$cos$\theta$ + $v_{1}$sin$\theta$ + $v_{2}$cos$\theta$ =  
= ($u_{1}$cos$\theta$ - $u_{2}$sin$\theta$, $u_{1}$sin$\theta$ + $u_{2}$cos$\theta$) + ($v_{1}$cos$\theta$ - $v_{2}$sin$\theta$, $v_{1}$sin$\theta$ + $v_{2}$cos$\theta$ ) =  
= r(u) + r(v)

** Se cumple la Propiedad 1. **

k * u = (k$u_{1}$, k$u_{2}$)

r(k*u) = (k * $u_{1}$cos$\theta$ - k * $u_{2}$sin$\theta$, k * $u_{1}$sin$\theta$ + k * $u_{2}$cos$\theta$) =  
= (k ( $u_{1}$cos$\theta$ - $u_{2}$sin$\theta$), k ( $u_{1}$sin$\theta$ - $u_{2}$cos$\theta$)) =  
= k (x*cos$\theta$ - y*sin$\theta$, x*sin$\theta$ + y*cos$\theta$) =  
= k r(u)

** Se cumple la Propiedad 2. **

** Por tanto la función rotación es LINEAL. **

<span style="color:blue"> Ejercicio 10:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

## De forma analítica:


x = [2, 2, 2, 3]
y = [1, 0, -1, 0]
z = [0, 1, 0, 1]
v = [6, 3, 2, 5]

A*x + B*y + C*z = v

2A + B = 6  
2A + C = 3  
2A - B = 2  
3A + C = 5  

A = 2  
B = 2  
C = -1

## De forma programática:

In [340]:

A = np.matrix([
    [2,1,0],
    [2,0,1],
    [2,-1,0],
    [3,0,1]
])
A_amp = np.matrix([
    [2,1,0,6],
    [2,0,1,3],
    [2,-1,0,2],
    [3,0,1,5]
])
detA_amp = np.linalg.det(A_amp)
detA_amp

print("El rango de la matriz de coeficientes es = " + str(np.linalg.matrix_rank(A)))
print("El rango de la matriz ampliada es = " + str(np.linalg.matrix_rank(A_amp)))

El rango de la matriz de coeficientes es = 3
El rango de la matriz ampliada es = 3


Es un sistema compatible determinado porque tenemos 3 incógnitas en el sistema y el rango de la matriz de coeficientes y la matriz ampliada es 3 también.

+ Como la matriz A no es cuadrada no es posible aplicar las funciones de determinante, inversa o resolución (solve)
+ Una opción es eliminar aleatoriamente una ecuación del sistema para hacer la matriz A cuadrada. En este caso se elimina la tercera ecuacion

In [345]:

A = np.matrix([
    [2,1,0],
    [2,0,1],
    [3,0,1]
])

B = np.matrix([
    [6],
    [3],
    [5]
])

#Resolución directa:
sol1 = np.linalg.solve(A,B)

#Resolucion matriz inversa:
invA = np.linalg.inv(A)
sol2 = invA * B
#Resolución metodo cramer:
AX = np.matrix([
    [6,1,0],
    [3,0,1],
    [5,0,1]
])
AY = np.matrix([
    [2,6,0],
    [2,3,1],
    [3,5,1]
])
AZ = np.matrix([
    [2,1,6],
    [2,0,3],
    [3,0,5]
])

x = np.linalg.det(AX) / np.linalg.det(A)
y = np.linalg.det(AY) / np.linalg.det(A)
z = np.linalg.det(AZ) / np.linalg.det(A)

sol = ([round(x), round(y), round(z)])
sol

[2.0, 2.0, -1.0]

<span style="color:blue"> Ejercicio 11:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

* Aristas : Pesos  
 A = {Pembroke Campus, Athletic Complex} : 7  
 B = {Pembroke Campus, Bio-Med} : 2  
 C = {Bio-Med, Athletic Complex} : 9  

Algoritmo Grow:

- Aristas en orden creciente según pesos: B, A, C

#1  
S: = ∅ 

#2  
S: = {B}

#3  
Hay que incluir el nodo Athletic Complex a través de la arista A o C.
Se selecciona el de menor peso.  
S: = {B,A}

Algoritmo Shrink:

- Aristas en orden decreciente según pesos: C, A, B

#1  
S: = {C, A, B}

#2  
Se puede eliminar la arista C porque existe un camino alternativo
S: = {A, B}

#3  
No se puede eliminar la arista A porque entonces el nodo Athletic Complex quedaría desconectado.
Por tanto, el mínimo bosque generador del grafo quedaría:
S: = {B,A}

<span style="color:blue"> Ejercicio 12:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [3]:
M = np.matrix([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])

np.linalg.matrix_rank(M)


3

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>

In [67]:
# Se importa la función division para que la division no devuelva entero (en python2)
from __future__ import division

def proyeccion_paralela(b, a):
    sigma = b.dot(a)/a.dot(a) if np.linalg.norm(z) > 10^-20 else 0
    return sigma * a

def proyeccion_ortogonal(b, a):
    return b - proyeccion_paralela(b, a)


In [70]:
a = np.array([6,2])
b = np.array([2,4])

print("Proyeccion Paralela de a sobre b:", proyeccion_paralela(b, a))
print("Proyeccion Perpendicular de a sobre b:", proyeccion_ortogonal(b, a))

('Proyeccion Paralela de a sobre b:', array([ 2.4,  0.8]))
('Proyeccion Perpendicular de a sobre b:', array([-1.4,  4.2]))
