# 1. Preliminares  

## Divaguemos...

Como decía un profesor mío de la universidad cuyo nombre dejaré en el anonimato:
* "*Las matemáticas no son un deporte para espectadores*". 

* "*Hay que acercarse a ellas con papel y lápiz*".

* "*Las matemáticas son una ciencia cuyo aprendizaje requiere esfuerzo y práctica y cuya recompensa se alcanza por la elegancia con la que permite resolver problemas propios y de otras Ciencias*".

¡Cuánta razón tenía! Sin las matemáticas no seríamos "nadie" en el mundo del **Big Data Analytics**.

Pero hay algo en lo que tendrá que perdonarme... No sólo aprendemos a día de hoy con papel y boli, aunque he de reconocer que a mí me sigue gustando muchas veces el método "de siempre".

En esta ocasión aprenderemos **Álgebra** con **Python**. Biennnnn!!!! 

Salvemos algún árbol de paso.

![No se puede mostrar](Images/Save-your-planet-label.png)





## ¿Qué es el Álgebra lineal?

El **Álgebra Lineal** es una rama de las matemáticas que estudia conceptos tales como vectores, matrices, tensores, sistemas de ecuaciones lineales y, en su enfoque más formal, espacios vetoriales y sus transformaciones lineales.





## ¿Por qué debemos estudiar Álgebra?

Una buena comprensión del **Álgebra lineal** es esencial para entender y trabajar con muchos algoritmos de **Machine Learning** y, especialmente, para los algoritmos de **Deep Learning**.

Muchos piensan que lo importante es sólo la Estadística, pero el **Álgebra Lineal** está a la par como una de las herramientas más usadas en **Big Data Analytics**.

Por tanto, si queremos volvernos auténticos expertos en el ámbito del análisis es importante reforzar los conceptos que forman parte de sus cimientos.

![No se puede mostrar](Images/smiley-faces-emojis.jpg)





## ¿Moriremos en el intento?

La respuesta es... que intentaremos que no. Simplemente es una extensión de lo que aprendimos en nuestra época pre-universitaria hacia un mayor número de dimensiones. 

Dicho de un modo más fromal, en lugar de trabajar con incógnitas a nivel de escalares comenzamos a trabajar con matrices y vectores.


## Números

Python puede utilizarse como calculadora

* *Suma*  
<span style="color:orange"> Ejemplo: Vamos a sumar 2+3</style>

In [1]:
2+3

5

* *Resta*  
<span style="color:orange"> Ejemplo: Vamos a restar 2-3</style>

In [3]:
2-3

-1

* *Multiplicación*  
<span style="color:orange"> Ejemplo: Vamos a multiplicar 2*3</style>

In [4]:
2*3

6

* *División*  
<span style="color:orange"> Ejemplo: Vamos a dividir 7 entre 2</style>

In [5]:
7/2

3.5

* *Parte entera de una división*  
<span style="color:orange"> Ejemplo: Vamos a sacar el cociente de la división de 7 entre 2</style>

In [6]:
7//2

3

* *Resto de una división*  
<span style="color:orange"> Ejemplo: Vamos a obtener el resto de la división de 7 entre 2</style>

In [7]:
7%2

1

* *Potencia*  
<span style="color:orange"> Ejemplo: Vamos a elevar 2 a la 3</style>

In [10]:
2**3

8

* *Redondear un número*  
<span style="color:orange"> Ejemplo: Vamos a redondear 4.14656</style>

*  <span style="color:orange"> Ejemplo: Ahora vamos a redondearlo con dos decimales</style>

In [16]:
round(4.14656,2)

4.15

* *Truncar*  
<span style="color:orange"> Ejemplo: Vamos a truncar este mismo número</style>

In [19]:
from math import floor
floor(4.14656)

4

* *Redondear al número superior*  
<span style="color:orange"> Ejemplo: Vamos redondear al número superior nuestro número</style>

In [22]:
from math import ceil
ceil(4.14656)

5

## Strings (Cadenas)

Sí, en Álgebra usamos letras y como tal, podemos usar "palabras"

<span style="color:orange"> Ejemplo: Vamos a escribir 'El Álgebra nos encanta'</style>

In [23]:
'El Álgebra nos encanta'

'El Álgebra nos encanta'

También podemos usar dobles comillas, que es muy útil cuando tenemos comillas simples en el texto.

<span style="color:orange"> Ejemplo: Vamos a escribir "Los 0's nos dan quebraderos de cabeza. ¿Por qué no se ponen de acuerdo de una vez con qué son o qué no son?"</style>

In [24]:
"Los 0's nos dan quebraderos de cabeza. ¿Por qué no se ponen de acuerdo de una vez con qué son o qué no son?"

"Los 0's nos dan quebraderos de cabeza. ¿Por qué no se ponen de acuerdo de una vez con qué son o qué no son?"

Por si alguno se lo pregunta, ¿que pasaría si intentase escribirlo con comillas simples?

In [25]:
'Los 0's nos dan quebraderos de cabeza. ¿Por qué no se ponen de acuerdo de una vez con qué son o qué no son?'

SyntaxError: invalid syntax (<ipython-input-25-bcb8543cffd6>, line 1)

## Instrucciones de comparación de valores (Booleanos)

Booleanos: True / False  
    
* *Igualdad*  

<span style="color:orange"> Ejemplo: Vamos a comparar 7 y 3</style>

In [27]:
7==3

False

Lo podría hacer con strings también

<span style="color:orange"> Ejemplo: Vamos a comparar el string Keepcoding con él mismo</style>

In [30]:
'Keepcoding'=='Keepcoding'

True

* *Mayor que*   
    >
* *Menor*   
    <
* *Mayor o igual que*  
    '>'=
* *Menor o igual que*   
    <=
* *Desigualdad*  
    !=
    
## AND, OR y NOT

<span style="color:orange"> Ejemplo: True and False</style>

In [31]:
True and False

False

<span style="color:orange"> Ejemplo: True and (7==3)</style>

In [33]:
True and (7==3)

False

<span style="color:orange"> Ejemplo: True or False</style>

In [32]:
True or False

True

<span style="color:orange"> Ejemplo: True and not (7==3)</style>

In [34]:
True and not (7==3)

True

## Condicionales

expresion **if** condicion **else** expresion 

<span style="color:orange"> Ejemplo: El valor absoluto de 3</style>

In [36]:
x=3
x if x>0 else -x

3

<span style="color:orange"> Ejemplo: El valor absoluto de -3</style>

In [37]:
x=-3
x if x>0 else -x

3

## Conjuntos

Un **conjunto** es una colección desordenada de objetos, que aparecen al menos una vez.

¿Esto qué quiere decir? Que si en el conjunto aparecen más de una vez, Python nos lo devolverá como un único objeto.

Los escribimos entre llaves.

<span style="color:orange"> Ejemplo: Escribamos el conjunto 2,1,3</style>


In [38]:
{2,1,3}

{1, 2, 3}

<span style="color:orange"> Ejemplo: Escribamos el conjunto 1+2, 3, 'a'</style>

In [39]:
{1+2,3,'a'}

{'a', 3}

<span style="color:orange"> Definamos el conjunto S como todos los enteros del -3 al 3 y obtengamos el conjunto de todos los que son mayores o iguales a 0</style>

In [41]:
S={-3,-2,-1,0,1,2,3}
{x for x in S if x>=0}

{0, 1, 2, 3}

La **cardinalidad** del conjunto S, expresada en Matemáticas como |S|, indica el número de elementos del conjunto S.

<span style="color:orange"> Ejemplo: Veamos la cardinalidad del conjunto a,b,c,a,a</style>

In [44]:
S={'a','b','c','a','a'}
len(S)

3

Podemos sumar los elementos de un conjunto, siempre y cuando sean valores.

<span style="color:orange"> Ejemplo: Sumemos el conjunto {2,4,6} y 5</style>

In [43]:
sum({2,4,6},5)

17

**$\in$** indica que un objeto pertenece a un conjunto

<span style="color:orange"> Ejemplo: Dado el conjunto S={1,2,3}, comprobemos si los elementos 2 y 7 pertenecen a él</style>

In [46]:
S={1,2,3}
2 in S

False

In [48]:
S={1,2,3}
7 in S

False

In [49]:
S={1,2,3}
7 not in S

True

La **unión** de dos conjuntos A y B es un nuevo conjunto que contiene los elementos que pertenecen a A y/o a B.

<span style="color:orange"> Ejemplo: Dados A={1,2,3} y B={3,4}, calcula AUB.</style>

In [50]:
{1,2,3} | {3,4}

{1, 2, 3, 4}

La **intersección** de dos conjuntos A y B es un nuevo conjunto que contiene los elementos que pertenecen a A y a B

<span style="color:orange"> Ejemplo: Dados A={1,2,3} y B={3,4}, calcula A$\cap$B.</style>

In [52]:
{1,2,3} & {3,4}

{3}

Los conjuntos son **mutables**  

<span style="color:orange"> Ejemplo: Dado A={1,2,3}, vamos a añadirle el elemento 4</style>

In [55]:
A={1,2,3}
A.add(4)
A

{1, 2, 3, 4}

<span style="color:orange"> Ejemplo: Ahora eliminamos el elemento 3</style>

In [56]:
A.remove(3)
A

{1, 2, 4}

<span style="color:orange"> Ejemplo: Ahora vamos a añadirle el conjunto {5,6,7,8}</style>

In [57]:
A.update({5,6,7,8})
A

{1, 2, 4, 5, 6, 7, 8}

Podemos quedarnos sólo con la intersección de nuestro conjunto con otro dado.

<span style="color:orange"> Ejemplo: Quedemos con la intersección de A con {7,8,9}</style>

In [58]:
A.intersection_update({7,8,9})
A

{7, 8}

**Conjuntos a partir de conjuntos**

Podemos crear nuevos conjuntos a partir de conjuntos ya definidos.

<span style="color:orange"> Ejemplo: Dado el conjunto A={1,2,3}, queremos crear el conjunto B como el resultado de multiplicar cada elemento de A por 3.</style>

In [59]:
A={1,2,3}
B={3*x for x in A}
B

{3, 6, 9}

## Listas

A diferencia de los conjuntos, en las **listas** el orden es importante y se permiten elementos repetidos.

Se expresa con corchetes.

<span style="color:orange"> Ejemplo: Escribamos la lista 1,1+1,3,2</style>

In [60]:
[1,1+1,3,2]

[1, 2, 3, 2]

Una lista puede contener distintos tipos de elementos.

<span style="color:orange"> Ejemplo: Escribamos la lista [1,1+1,4-1],{2*2,5,6},'yo'</style>

In [61]:
[[1,1+1,4-1],{2*2,5,6},'yo']

[[1, 2, 3], {4, 5, 6}, 'yo']

La **cardinalidad** de una lista se calcula igual que en los conjuntos.

<span style="color:orange"> Ejemplo: Calculemos la cardinalidad de la lista anterior</style>

In [62]:
len([[1,1+1,4-1],{2*2,5,6},'yo'])

3

Vamos a ver qué podemos hacer con las listas.

<span style="color:orange"> Ejemplo: Vamos a crear la lista TBBT con los elementos Sheldon, Leonard, Penny, Raj, Howard</style>

In [64]:
TBBT=['Sheldon', 'Leonard', 'Penny','Raj', 'Howard']
TBBT

['Sheldon', 'Leonard', 'Penny', 'Raj', 'Howard']

<span style="color:orange"> Ejemplo: Vamos a añadir a la lista a Bernadette</style>

In [65]:
TBBT.append('Bernadette')
TBBT

['Sheldon', 'Leonard', 'Penny', 'Raj', 'Howard', 'Bernadette']

<span style="color:orange"> Ejemplo: Queremos conocer quién está en la posición 1 de la lista TBBT</style>

In [66]:
TBBT[1]

'Leonard'

¿Cómo? ¡Cuidado! Empezamos la lista en la posición 0

<span style="color:orange"> Ejemplo: Queremos conocer quién está en la posición 0 de la lista TBBT</style>

In [67]:
TBBT[0]

'Sheldon'

<span style="color:orange"> Ejemplo: Queremos conocer en qué posición está Raj</style>

In [69]:
TBBT.index('Raj')

3

Podemos cambiar cualquier elemento de la lista simplemente declarándolo.

<span style="color:orange"> Ejemplo: Vamos a cambiar a Raj que está en la posición 3 por Amy</style>

In [70]:
TBBT[3]='Amy'
TBBT

['Sheldon', 'Leonard', 'Penny', 'Amy', 'Howard', 'Bernadette']

<span style="color:orange"> Ejemplo: Queremos volver a añadir a Raj justo después de Amy</style>

In [80]:
TBBT.insert(4,'Raj')
TBBT

['Sheldon', 'Leonard', 'Penny', 'Amy', 'Raj', 'Howard', 'Bernadette']

<span style="color:orange"> Ejemplo: Queremos eliminar a Raj. ¡¡Pobre!!</style>

In [81]:
TBBT.remove('Raj')
TBBT

['Sheldon', 'Leonard', 'Penny', 'Amy', 'Howard', 'Bernadette']

<span style="color:orange"> Ejemplo: Por si alguno se ha despistado, vamos a comprobar si Raj está en la lista.</style>

In [82]:
'Raj' in TBBT

False

<span style="color:orange"> Ejemplo: Ordenemos nuestra lista</style>

In [83]:
TBBT.sort()
TBBT

['Amy', 'Bernadette', 'Howard', 'Leonard', 'Penny', 'Sheldon']

<span style="color:orange"> Ejemplo: si quisiésemos ordenarla en modo descendente.</style>

In [84]:
TBBT.sort(reverse=True)
TBBT

['Sheldon', 'Penny', 'Leonard', 'Howard', 'Bernadette', 'Amy']

## Tuplas

Las **tuplas** son un tipo de lista un poco especial, no mutable, es decir, no se puede modificar lo que tienen.  
Se podría decir que son iguales que las listas pero no podemos alterar su contenido.  
Se declaran con paréntesis.  

<span style="color:orange"> Ejemplo: Vamos a crear la tupla TBBT con los elementos Sheldon, Leonard, Penny, Raj, Howard</style>

In [85]:
TBBT=('Sheldon', 'Leonard', 'Penny','Raj', 'Howard')
TBBT

('Sheldon', 'Leonard', 'Penny', 'Raj', 'Howard')

<span style="color:orange"> Ejemplo: Queremos conocer quién está en la posición 1 de la tupla TBBT</style>

In [87]:
TBBT[1]

'Leonard'

## Diccionarios

Los **diccionarios** son una estructura que almacena los elementos a los que se les da un nombre o clave (key).  
De esta forma, en vez de acceder al elemento por medio del índice que ocupa, se accede a él por el nombre que tiene.  
Podemos definir un diccionario como un conjunto de parejas clave-valor, donde la clave es el nombre que se le da a un valor.  
Los valores de un diccionario pueden tener cualquier forma: números, strings, listas,..

<span style="color:orange"> Ejemplo: Veamos un diccionario sencillo, que consiste en los pronombre personales en singular en español y en inglés</style>

In [88]:
pronombres={'yo':'I', 'tú': 'You', 'él': 'He'}
pronombres

{'tú': 'You', 'yo': 'I', 'él': 'He'}

<span style="color:orange"> Ejemplo: Queremos obtener lo que tiene guardado el diccionario pronombres para "yo"</style>

In [89]:
pronombres['yo']

'I'

Para añadir nuevas parejas clave-valor sólo tenemos que indicarlo.

<span style="color:orange"> Ejemplo: Añadamos a nuestro diccionario 'ella' con su traducción 'She'</style>

In [90]:
pronombres['ella']='She'
pronombres

{'ella': 'She', 'tú': 'You', 'yo': 'I', 'él': 'He'}

Para recorrer un diccionario, veámoslo con un ejemplo.

<span style="color:orange"> Ejemplo: Vamos a recorrer nuestro diccionario pronombres</style>

In [93]:
pronombres={'yo':'I', 'tú': 'You', 'él': 'He', 'ella': 'She'}
for clave, valor in pronombres.items():
    print('La traducción de '+ clave + ' es ' + valor)

La traducción de yo es I
La traducción de tú es You
La traducción de él es He
La traducción de ella es She


## Objetos matemáticos en Álgebra Lineal

* *Escalares*  
    Un escalar es un solo número, en contraposición al resto de objetos que suelen ser una colección de múltiples números
    
    <span style="color:orange"> Ejemplo: Vamos a mostrar el escalar 1 </style>


In [6]:
escalar=1
escalar

1

* *Vectores*  
    Un vector es una serie de elementos ordenados.  
    ¡Cuidado! No significa ordenados numéricamente, sino en función de un índice de orden.  
    
<span style="color:orange"> Ejemplo: Vamos a mostrar el vector v1 (2,5,6) como lista en Python </style>  



In [5]:
v1= [2,4,6]
v1

[2, 4, 6]

<span style="color:orange"> Ejemplo: Vamos a mostrar ahora este mismo vector v1 con numpy </style>  

In [7]:
import numpy as np
v1=[2,4,6]
v1

[2, 4, 6]

Da lo mismo...  

<span style="color:orange"> Ejemplo: ¿y si quisiésemos crear un vector v2 como una tupla de tres unos? </style>  

In [8]:
import numpy as np
v2=np.ones(3)
v2

array([ 1.,  1.,  1.])

¿Y si quisiésemos pasarle una lista para crear el array a numpy?

<span style="color:orange"> Ejemplo: Pasemos la lista 1, 4, 7 a un array v3 de numpy </style> 

In [9]:
import numpy as np
v3= np.array([1,4,7])
v3

array([1, 4, 7])

<span style="color:orange"> Ejemplo: ¿Y si queremos crear un vector con la lista de los diez primeros números? </style> 

In [10]:
import numpy as np
v4=np.arange(1,11)
v4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* *Matrices*  
Es un arreglo bidimensional de elementos ordenados en filas y columnas.  
Cada elemento de la matriz puede ser identificado utilizando dos índices, uno para la fila y otro para la columna en la que se encuentra.  
Una matriz se dice que es de orden nxm (filas x columnas). 

<span style="color:orange"> Ejemplo: Vamos a dibujar una matriz 3x3</style>

In [12]:
import numpy as np
A=np.array([[1,2,3], [1,0,0], [6,7,8]])
A

array([[1, 2, 3],
       [1, 0, 0],
       [6, 7, 8]])

* *Tensores*  
Son matrices con más de dos ejes.  
En general, es una serie de elementos dispuestos en una cuadrícula regular con un número variable de ejes.  
<span style="color:violet"> NOTA: Es un tema complicado, que se escapa al Álgebra Lineal del módulo. Se hablará muuuuucho sobre ello en Deep Learning.  
De momento quédemonos con saber de su existencia.</style>

## Librerías en Python para Álgebra Lineal

* *Numpy*  
    Nos va a permitir crear vectores, matrices y tensores con suma facilidad
* *numpy.linalg*  
    Submódulo dentro de *Numpy* con un gran número de funciones para resolver ecuaciones
* *scipy.linalg*  
    Submódulo de *Scipy* similar al anterior, pero con algunas más funciones y optimizaciones
* *Sympy*  
    Nos permite trabajar con matemática simbólica.
* *CVXOPT*  
    Nos permite resolver problemas de optimizaciones de programación lineal
* *PuLP*
    Nos permite crear modelos de programación lineal de una manera muy sencilla 